package analisador_lexico;

public enum Tokens {
    //Tokens criados na classe de regras (Regras.flex) definidos como enum para organização e utilização pela programa principal
    LETRA, DIGITO, RESERVADO, SEPARADOR, RESERVADO_NULL, RESERVADO_IF, RESERVADO_WHILE, RESERVADO_TRY, RESERVADO_CATCH, RESERVADO_FINALLY, 
    RESERVADO_FOR, RESERVADO_ELSE, EXCECAO, TIPO, TIPO_NUMERICO, OPERADOR_ARITMETICO, OPERADOR_ATRIBUICAO, OPERADOR_AUTO_INCREMENTO, OPERADOR_RELACIONAL,
    OPERADOR_ATRIBUICAO_IGUAL, OPERADOR_RELACIONAL_IGUAL_DIFERENTE, SEPARADOR_PARENTESE_ABRE, SEPARADOR_PARENTESE_FECHA, SEPARADOR_CHAVE_ABRE,
    SEPARADOR_CHAVE_FECHA, SEPARADOR_PONTO_VIRGULA, ASPAS, OPERADOR_LOGICO, OPERADOR_BOOLEANO, ESPACO, ID, NUMERO, ERROR;
}
