
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisador_sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR_RELACIONAL_IGUAL_DIFERENTE = 19;
  public static final int ASPAS = 27;
  public static final int RESERVADO_FOR = 10;
  public static final int OPERADOR_RELACIONAL = 15;
  public static final int SEPARADOR_CHAVE_FECHA = 25;
  public static final int SEPARADOR_PARENTESE_FECHA = 23;
  public static final int RESERVADO_CATCH = 7;
  public static final int ERROR = 2;
  public static final int RESERVADO_FINALLY = 9;
  public static final int EXCECAO = 11;
  public static final int ID = 18;
  public static final int RESERVADO_NULL = 3;
  public static final int SEPARADOR_PONTO_VIRGULA = 26;
  public static final int TIPO = 12;
  public static final int OPERADOR_BOOLEANO = 17;
  public static final int OPERADOR_AUTO_INCREMENTO = 28;
  public static final int EOF = 0;
  public static final int OPERADOR_ARITMETICO = 13;
  public static final int OPERADOR_ATRIBUICAO = 14;
  public static final int RESERVADO_ELSE = 8;
  public static final int SEPARADOR_CHAVE_ABRE = 24;
  public static final int NUMERO = 29;
  public static final int RESERVADO_WHILE = 5;
  public static final int error = 1;
  public static final int RESERVADO_TRY = 6;
  public static final int OPERADOR_LOGICO = 16;
  public static final int RESERVADO_IF = 4;
  public static final int SEPARADOR_PARENTESE_ABRE = 22;
  public static final int TIPO_NUMERICO = 21;
  public static final int OPERADOR_ATRIBUICAO_IGUAL = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "RESERVADO_NULL",
  "RESERVADO_IF",
  "RESERVADO_WHILE",
  "RESERVADO_TRY",
  "RESERVADO_CATCH",
  "RESERVADO_ELSE",
  "RESERVADO_FINALLY",
  "RESERVADO_FOR",
  "EXCECAO",
  "TIPO",
  "OPERADOR_ARITMETICO",
  "OPERADOR_ATRIBUICAO",
  "OPERADOR_RELACIONAL",
  "OPERADOR_LOGICO",
  "OPERADOR_BOOLEANO",
  "ID",
  "OPERADOR_RELACIONAL_IGUAL_DIFERENTE",
  "OPERADOR_ATRIBUICAO_IGUAL",
  "TIPO_NUMERICO",
  "SEPARADOR_PARENTESE_ABRE",
  "SEPARADOR_PARENTESE_FECHA",
  "SEPARADOR_CHAVE_ABRE",
  "SEPARADOR_CHAVE_FECHA",
  "SEPARADOR_PONTO_VIRGULA",
  "ASPAS",
  "OPERADOR_AUTO_INCREMENTO",
  "NUMERO"
  };
}

